### ISSUE TITLE
Also have the PR to jasp-desktop to the module

### ISSUE THREAD

**Issue by AlexanderLyNL** [jasp-stats/jaspTTests#6]
Hi Johnny, 

Can you also do the following PR into this module? 

    https://github.com/jasp-stats/jasp-desktop/pull/4228

aka this repository

    jasp-stats/jaspTTests 

@TimKDJ that's correct isn't it?

Cheers,
Alexander

**Comment by TimKDJ** [comment]
Added in https://github.com/jasp-stats/jaspTTests/commit/58b8066aa8fa8e9dd8f9c01f4c61a1257371fa8d
