### ISSUE TITLE
Missing .BANOVAdependentName and .BANOVAsubjectName

### ISSUE THREAD

**Issue by TimKDJ** [jasp-stats/jaspTTests#9]
`.BANOVAdependentName` and `.BANOVAsubjectName` are not in jaspTTests, but they are in jaspAnova.
I originally moved `.summarySE()` and `summarySEwithin()` to this module to avoid circular dependencies between jaspAnova and jaspTTests.
Should a copy of these functions exist in both or do we reckon they're important enough to give a few hacky arguments?
@vandenman

**Comment by vandenman** [comment]
can't we rewrite `.BANOVAsubjectName` so that it doesn't hardcode `.BANOVAsubjectName`? Then both modules just call the function with whatever arguments they deem necessary.

**Comment by TimKDJ** [comment]
Ya that's what I meant with a few hacky arguments :P
